[book]
title = "Fungi Protocol Suite"
language = "en"
src = "src"

[preprocessor.jupyter]
command = "python3 contrib/jupyter_nb.py"
before = ["graphviz", "mermaid", "katex"]

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.mermaid]
command = "python3 contrib/mermaid_ssr.py"

[preprocessor.katex]
command = "mdbook-katex"

[output.html]
additional-css = ["theme/diagrams.css"]
